import { Ticket, PRIORITY_SLA } from './ticketing-data';

function isoFromOffset(hoursOffset: number): string {
  const d = new Date(Date.now() + hoursOffset * 3600 * 1000);
  return d.toISOString();
}

export const SEED_TICKETS: Ticket[] = [
  {
    id: 'TKT-1042',
    title: 'AC malfunctioning in Studio 2 during 7AM Barre 57',
    description: 'Member reported the AC was barely cooling during the 7AM Barre 57 class. Multiple members complained mid-class. Trainer Karishma flagged it to front desk after the session.',
    category: 'Facility & Equipment',
    subCategory: 'AC / Temperature',
    priority: 'High',
    status: 'In Progress',
    studio: 'Kwality House, Kemps Corner',
    trainer: 'Karishma Hingorani',
    classType: 'Barre 57',
    classDateTime: isoFromOffset(-3),
    memberName: 'Anjali Mehra',
    reportedBy: 'Priya Sharma',
    assignedTo: 'Rahul Mehta',
    team: 'Operations',
    tags: ['hvac', 'urgent', 'multi-member'],
    createdAt: isoFromOffset(-2.5),
    slaDueAt: isoFromOffset(5.5),
    sentiment: 'Negative',
  },
  {
    id: 'TKT-1043',
    title: 'Compliment for Tanisha Ahuja - exceptional Power Cycle class',
    description: 'Member wrote in to compliment Tanisha for an "incredibly motivating" Power Cycle class. Wants to ensure feedback reaches her and management.',
    category: 'Instructor & Class Quality',
    subCategory: 'Trainer Behavior',
    priority: 'Low',
    status: 'New',
    studio: 'Bandra West',
    trainer: 'Tanisha Ahuja',
    classType: 'Power Cycle',
    memberName: 'Karan Bhandari',
    reportedBy: 'Aditya Verma',
    assignedTo: 'Sanya Iyer',
    team: 'Instruction',
    tags: ['compliment', 'recognition'],
    createdAt: isoFromOffset(-1),
    slaDueAt: isoFromOffset(71),
    sentiment: 'Positive',
  },
  {
    id: 'TKT-1044',
    title: 'Duplicate charge of ₹8,499 on membership renewal',
    description: 'Member was charged twice for her quarterly renewal on May 12. Bank statement attached. Requests immediate refund.',
    category: 'Billing & Membership',
    subCategory: 'Incorrect Charge',
    priority: 'High',
    status: 'Awaiting Member',
    studio: 'Juhu',
    memberName: 'Riya Kapoor',
    memberContact: '+91 98xxx xxx12',
    reportedBy: 'Neha Kapoor',
    assignedTo: 'Neha Kapoor',
    team: 'Finance',
    tags: ['refund', 'duplicate-charge', 'finance'],
    createdAt: isoFromOffset(-5),
    slaDueAt: isoFromOffset(3),
    sentiment: 'Angry',
  },
  {
    id: 'TKT-1045',
    title: 'Minor slip during Cardio Barre - member checked, no injury',
    description: 'Member slipped near the barre during a transition. Trainer Rohan responded immediately. No injury reported but floor was found to be slightly damp. Cleaning protocol review requested.',
    category: 'Safety & Medical',
    subCategory: 'Slip / Fall',
    priority: 'Critical',
    status: 'In Progress',
    studio: 'Lower Parel',
    trainer: 'Rohan Dahima',
    classType: 'Cardio Barre',
    classDateTime: isoFromOffset(-6),
    memberName: 'Devika Suri',
    reportedBy: 'Vikram Singh',
    assignedTo: 'Vikram Singh',
    team: 'Operations',
    tags: ['safety', 'incident-report', 'cleaning'],
    createdAt: isoFromOffset(-5.5),
    slaDueAt: isoFromOffset(-3.5),
    sentiment: 'Negative',
  },
  {
    id: 'TKT-1046',
    title: 'App crashes when booking waitlisted Power Cycle',
    description: 'Member reported the iOS app crashes the moment she taps "Join Waitlist" for Power Cycle classes. Reproduced on iPhone 13, iOS 17.4.',
    category: 'App & Digital',
    subCategory: 'App Crash',
    priority: 'Medium',
    status: 'New',
    studio: 'Powai',
    memberName: 'Sneha Iyer',
    reportedBy: 'Arjun Nair',
    assignedTo: 'Arjun Nair',
    team: 'IT',
    tags: ['ios', 'waitlist', 'crash'],
    createdAt: isoFromOffset(-0.5),
    slaDueAt: isoFromOffset(23.5),
    sentiment: 'Neutral',
  },
  {
    id: 'TKT-1047',
    title: 'Request to freeze membership for 6 weeks - medical',
    description: 'Member is undergoing knee physiotherapy and has requested a 6-week medical freeze on her unlimited package. Doctor note shared via email.',
    category: 'Billing & Membership',
    subCategory: 'Membership Freeze',
    priority: 'Medium',
    status: 'In Progress',
    studio: 'Delhi - Khan Market',
    memberName: 'Priyanka Sethi',
    reportedBy: 'Meera Joshi',
    assignedTo: 'Neha Kapoor',
    team: 'Finance',
    tags: ['freeze', 'medical', 'documentation'],
    createdAt: isoFromOffset(-12),
    slaDueAt: isoFromOffset(12),
    sentiment: 'Neutral',
  },
  {
    id: 'TKT-1048',
    title: 'Late cancellation fee disputed - member was unwell',
    description: 'Member was charged ₹500 late cancellation fee for a Barre 57 class she could not attend due to a fever. Requests waiver as a one-time exception.',
    category: 'Booking & Schedule',
    subCategory: 'Late Cancellation Fee',
    priority: 'Medium',
    status: 'New',
    studio: 'Bengaluru - Indiranagar',
    classType: 'Barre 57',
    memberName: 'Aarav Kulkarni',
    reportedBy: 'Priya Sharma',
    assignedTo: 'Priya Sharma',
    team: 'Operations',
    tags: ['waiver-request', 'goodwill'],
    createdAt: isoFromOffset(-3),
    slaDueAt: isoFromOffset(21),
    sentiment: 'Negative',
  },
  {
    id: 'TKT-1049',
    title: 'Locker #14 jammed - member could not retrieve belongings',
    description: 'Member could not open Locker #14 after her Mat 57 class. Took 35 minutes to escalate to facility. Member wants assurance this won\'t recur.',
    category: 'Facility & Equipment',
    subCategory: 'Locker / Changing Room',
    priority: 'High',
    status: 'Resolved',
    studio: 'Bandra West',
    classType: 'Mat 57',
    memberName: 'Tanvi Rao',
    reportedBy: 'Rahul Mehta',
    assignedTo: 'Rahul Mehta',
    team: 'Operations',
    tags: ['locker', 'facility', 'resolved'],
    createdAt: isoFromOffset(-26),
    slaDueAt: isoFromOffset(-18),
    sentiment: 'Negative',
  },
  {
    id: 'TKT-1050',
    title: 'Music volume too low in 6PM Strength Lab',
    description: 'Multiple members felt the music was barely audible during the 6PM Strength Lab. Trainer Imran also confirmed. Sound system check requested.',
    category: 'Facility & Equipment',
    subCategory: 'Sound System',
    priority: 'Low',
    status: 'New',
    studio: 'Kwality House, Kemps Corner',
    trainer: 'Imran Khan',
    classType: 'Strength Lab',
    reportedBy: 'Aditya Verma',
    assignedTo: 'Rahul Mehta',
    team: 'Operations',
    tags: ['audio', 'sound'],
    createdAt: isoFromOffset(-8),
    slaDueAt: isoFromOffset(64),
    sentiment: 'Neutral',
  },
  {
    id: 'TKT-1051',
    title: 'Substitute trainer mismatch - member expected Mrigakshi',
    description: 'Member booked specifically for Mrigakshi Jaiswal\'s class and found a substitute without prior notice. Requests a credit and process review.',
    category: 'Instructor & Class Quality',
    subCategory: 'Substitute Trainer Issue',
    priority: 'Medium',
    status: 'In Progress',
    studio: 'Juhu',
    trainer: 'Mrigakshi Jaiswal',
    classType: 'Barre 57',
    memberName: 'Ishaan Bhagat',
    reportedBy: 'Sanya Iyer',
    assignedTo: 'Sanya Iyer',
    team: 'Instruction',
    tags: ['substitute', 'communication-gap'],
    createdAt: isoFromOffset(-15),
    slaDueAt: isoFromOffset(9),
    sentiment: 'Negative',
  },
  {
    id: 'TKT-1052',
    title: 'Suggestion: add a recovery / stretch class on Sundays',
    description: 'Long-time member suggested adding a Recovery & Mobility class on Sunday mornings. Says she\'d bring 3-4 friends.',
    category: 'General Feedback',
    subCategory: 'New Feature Request',
    priority: 'Low',
    status: 'New',
    studio: 'Delhi - Vasant Vihar',
    classType: 'Recovery & Mobility',
    memberName: 'Roshni Kapoor',
    reportedBy: 'Aditya Verma',
    assignedTo: 'Aditya Verma',
    team: 'CX',
    tags: ['suggestion', 'programming', 'growth'],
    createdAt: isoFromOffset(-20),
    slaDueAt: isoFromOffset(52),
    sentiment: 'Positive',
  },
  {
    id: 'TKT-1053',
    title: 'Towel service ran out mid-morning at Powai',
    description: 'Members during the 10AM and 11AM slots reported no fresh towels available. Front desk had to redirect to retail towels.',
    category: 'Front Desk & Service',
    subCategory: 'Towel / Amenity',
    priority: 'Medium',
    status: 'Resolved',
    studio: 'Powai',
    reportedBy: 'Priya Sharma',
    assignedTo: 'Rahul Mehta',
    team: 'Operations',
    tags: ['amenity', 'inventory'],
    createdAt: isoFromOffset(-30),
    slaDueAt: isoFromOffset(-6),
    sentiment: 'Negative',
  },
];

export function computePriorityFromCategory(category: string, subCategory: string): Ticket['priority'] {
  if (category === 'Safety & Medical') return 'Critical';
  if (subCategory.toLowerCase().includes('refund') || subCategory.toLowerCase().includes('incorrect charge')) return 'High';
  if (category === 'Facility & Equipment') return 'High';
  if (category === 'General Feedback') return 'Low';
  return 'Medium';
}

export function generateTicketId(): string {
  return `TKT-${1054 + Math.floor(Math.random() * 9000)}`;
}

export function computeSlaDueAt(priority: Ticket['priority']): string {
  const hours = PRIORITY_SLA[priority].hours;
  return new Date(Date.now() + hours * 3600 * 1000).toISOString();
}
